/* Generated By:JavaCC: Do not edit this line. compiladorConstants.java */
package br.edu.udc.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 5;
  /** RegularExpression Id. */
  int NUMERO = 6;
  /** RegularExpression Id. */
  int DIGITO = 7;
  /** RegularExpression Id. */
  int LETRA = 8;
  /** RegularExpression Id. */
  int TIPO = 9;
  /** RegularExpression Id. */
  int OPERADOR_MATEMATICO = 10;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<IDENTIFICADOR>",
    "<NUMERO>",
    "<DIGITO>",
    "<LETRA>",
    "<TIPO>",
    "<OPERADOR_MATEMATICO>",
    "<OPERADOR_LOGICO>",
    "\"START\"",
    "\";\"",
    "\">>\"",
    "\",\"",
    "\"<-\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"FOR\"",
    "\"TO\"",
    "\"<<\"",
  };

}
