/* Generated By:JavaCC: Do not edit this line. AdderConstants.java */
package JavaCC.Adder;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 2;
  /** RegularExpression Id. */
  int OPERADOR = 3;
  /** RegularExpression Id. */
  int SOMA = 4;
  /** RegularExpression Id. */
  int SUBTRACAO = 5;
  /** RegularExpression Id. */
  int DIVISAO = 6;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 7;
  /** RegularExpression Id. */
  int PARENT = 8;
  /** RegularExpression Id. */
  int PARENTE = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<NUMBER>",
    "<OPERADOR>",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
